env:
  - BUILD_ARCH=x86_64
  - BUILD_ARCH=armhf
dist: trusty
language: generic
sudo: required
install:
  - sudo BUILD_ARCH=${BUILD_ARCH} .travis/install-alpine
  - sudo .travis/setup-alpine
script: |
  source .travis/common.sh
  alpine_run $USER .travis/build-pkgs
notifications:
  email: false
